projects:
  ChatApp:
    schemaPath: graphql/schema.json
    includes:
      - queries/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: queries/index.ts
        docsFilePath: queries
        region: eu-west-2
        apiId: i3y4evjdvbenvfy32tc3eovbzq
        maxDepth: 2
extensions:
  amplify:
    version: 3
